package rs.ac.bg.fon.nprog.server.forms;

import javax.swing.JFrame;
import javax.swing.JPanel;
import rs.ac.bg.fon.nprog.common.domain.Administrator;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import rs.ac.bg.fon.nprog.server.modeli.TableModelAdmini;

public class FrmMainServer extends JFrame {

	ArrayList<Administrator> administratori;

	/**
	 * Creates new form FrmMainServer
	 */
	public FrmMainServer() {
		initComponents();
		setModelTable();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		lblProgramName = new javax.swing.JLabel();
		lblNameSurname = new javax.swing.JLabel();
		btnStartServer = new javax.swing.JButton();
		btnStopServer = new javax.swing.JButton();
		lbl = new javax.swing.JLabel();
		lblStatus = new javax.swing.JLabel();
		panelAdministratori = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tblAdministratori = new javax.swing.JTable();
		jMenuBar = new javax.swing.JMenuBar();
		jMenuSettings = new javax.swing.JMenu();
		jMenuItemServer = new javax.swing.JMenuItem();
		jMenuItemDataBase = new javax.swing.JMenuItem();
		jMenuAbout = new javax.swing.JMenu();
		jMenuItemAboutSoftware = new javax.swing.JMenuItem();

		jTable1.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Server application");

		lblProgramName.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
		lblProgramName.setText("Škola stranih jezika");

		lblNameSurname.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
		lblNameSurname.setText("Maja Čolović 2017/0123");

		btnStartServer.setText("Start server");

		btnStopServer.setText("Stop server");

		lbl.setText("Status:");

		lblStatus.setText("jLabel1");

		panelAdministratori.setBorder(javax.swing.BorderFactory.createTitledBorder("Prijavljeni administratori"));

		tblAdministratori
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane2.setViewportView(tblAdministratori);

		javax.swing.GroupLayout panelAdministratoriLayout = new javax.swing.GroupLayout(panelAdministratori);
		panelAdministratori.setLayout(panelAdministratoriLayout);
		panelAdministratoriLayout.setHorizontalGroup(
				panelAdministratoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE));
		panelAdministratoriLayout.setVerticalGroup(
				panelAdministratoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panelAdministratoriLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jMenuSettings.setText("Settings");

		jMenuItemServer.setText("Server");
		jMenuSettings.add(jMenuItemServer);

		jMenuItemDataBase.setText("DataBase");
		jMenuSettings.add(jMenuItemDataBase);

		jMenuBar.add(jMenuSettings);

		jMenuAbout.setText("About");

		jMenuItemAboutSoftware.setText("About software");
		jMenuAbout.add(jMenuItemAboutSoftware);

		jMenuBar.add(jMenuAbout);

		setJMenuBar(jMenuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(panelAdministratori, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblProgramName, javax.swing.GroupLayout.PREFERRED_SIZE,
														172, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE,
														185, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(55, 55, 55)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnStartServer).addComponent(btnStopServer)))
								.addGroup(layout.createSequentialGroup().addComponent(lbl).addGap(18, 18, 18)
										.addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 242,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(0, 0, Short.MAX_VALUE)))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblProgramName).addComponent(btnStartServer))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lblNameSurname))
								.addGroup(
										layout.createSequentialGroup().addGap(14, 14, 14).addComponent(btnStopServer)))
						.addGap(16, 16, 16)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl).addComponent(lblStatus))
						.addGap(18, 18, 18)
						.addComponent(panelAdministratori, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FrmMainServer.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FrmMainServer.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FrmMainServer.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FrmMainServer.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FrmMainServer().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnStartServer;
	private javax.swing.JButton btnStopServer;
	private javax.swing.JMenu jMenuAbout;
	private javax.swing.JMenuBar jMenuBar;
	private javax.swing.JMenuItem jMenuItemAboutSoftware;
	private javax.swing.JMenuItem jMenuItemDataBase;
	private javax.swing.JMenuItem jMenuItemServer;
	private javax.swing.JMenu jMenuSettings;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JLabel lbl;
	private javax.swing.JLabel lblNameSurname;
	private javax.swing.JLabel lblProgramName;
	private javax.swing.JLabel lblStatus;
	private javax.swing.JPanel panelAdministratori;
	private javax.swing.JTable tblAdministratori;
	// End of variables declaration

	public JButton getBtnStartServer() {
		return btnStartServer;
	}

	public JButton getBtnStopServer() {
		return btnStopServer;
	}

	public JMenuItem getjMenuItemDataBase() {
		return jMenuItemDataBase;
	}

	public JMenuItem getjMenuItemServer() {
		return jMenuItemServer;
	}

	public JLabel getLblStatus() {
		return lblStatus;
	}

	public JTable getTblAdministratori() {
		return tblAdministratori;
	}

	public JPanel getPanelAdministratori() {
		return panelAdministratori;
	}

	public void addBtnStartServerActionListener(ActionListener actionListener) {
		btnStartServer.addActionListener(actionListener);
	}

	public void addBtnStopServerActionListener(ActionListener actionListener) {
		btnStopServer.addActionListener(actionListener);
	}

	public void addBtnJMIServerActionListener(ActionListener actionListener) {
		jMenuItemServer.addActionListener(actionListener);
	}

	public void addBtnJMIDataBaseActionListener(ActionListener actionListener) {
		jMenuItemDataBase.addActionListener(actionListener);
	}

	public void prijaviAdministratora(Administrator a) {
		TableModelAdmini tb = (TableModelAdmini) tblAdministratori.getModel();
		tb.loginAdmin(a);
	}

	public void odjaviAdministratora(Administrator a) {
		TableModelAdmini tb = (TableModelAdmini) tblAdministratori.getModel();
		tb.logoutAdmin(a);
	}

	public List<Administrator> vratiPrijavljeneAdministratore() {
		TableModelAdmini tb = (TableModelAdmini) tblAdministratori.getModel();
		return tb.vratiAdmine();
	}

	private void setModelTable() {
		TableModelAdmini tm = new TableModelAdmini(new ArrayList<>());
		tblAdministratori.setModel(tm);
	}

}
